<?php
/**
 * @category   Test
 * @package    Test_Demo
 * @author     mohitvamja1991@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Test\Demo\Controller\Index;
use Magento\Framework\App\Action\Context;
use Magento\Framework\App\ResponseInterface;
use Test\Demo\Model\ClassDefault;

class Typetwo extends \Magento\Framework\App\Action\Action
{
	protected $classDefault;

    public function __construct(
        Context $context,
        ClassDefault $classDefault
    )
    {
        $this->classDefault = $classDefault;
        parent::__construct($context);
    }

    public function execute()
    {
        echo "Submit ClassA Namespace : ".$this->classDefault->namespace;
    } 
}
