<?php
/**
 * @category   Test
 * @package    Test_Demo
 * @author     mohitvamja1991@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Test\Demo\Model\Source;

class Customdropdown extends \Magento\Eav\Model\Entity\Attribute\Source\AbstractSource 
{
     public function getAllOptions() 
     {
         if ($this->_options === null) {

         $this->_options = [

         ['value' => '', 'label' => __('Please Select')],

         ['value' => '1', 'label' => __('Google')],

         ['value' => '2', 'label' => __('Friend')],

         ['value' => '3', 'label' => __('Email')],

         ['value' => '4', 'label' => __('Other')]

         ];

         }

         return $this->_options;

     }

     public function getOptionText($value) 
     {
         foreach ($this->getAllOptions() as $option)
         {
             if ($option['value'] == $value)
             {
                return $option['label'];
             }
         }
         return false;
     }
}